'use client'
import { useEffect } from 'react'

interface Guest {
  id: string
  name: string
  category: string
  rsvp_status: string
}

interface SeatingAssignment {
  id: string
  guests: Guest
}

interface Table {
  id: string
  name: string
  max_seats: number
  seating_assignments: SeatingAssignment[]
}

interface Wedding {
  couple_names: string
  event_date: string | null
  venue_name: string | null
}

interface Props {
  wedding: Wedding | null
  tables: Table[]
}

export default function PrintSeating({ wedding, tables }: Props) {
  useEffect(() => {
    window.print()
  }, [])

  const getGuestCount = (table: Table) =>
    table.seating_assignments.reduce((sum, a) =>
      sum + (a.guests?.category === 'couple' ? 2 : 1), 0
    )

  const totalGuests = tables.reduce(
    (sum, t) => sum + getGuestCount(t), 0
  )

  return (
    <div className="p-8 max-w-4xl mx-auto font-sans">
      {/* Header */}
      <div className="text-center mb-8 pb-6 border-b border-gray-200">
        <h1 className="text-3xl font-bold text-gray-900 mb-1">
          {wedding?.couple_names}
        </h1>
        <p className="text-gray-500">Seating Arrangement</p>
        {wedding?.event_date && (
          <p className="text-gray-400 text-sm mt-1">
            {new Date(wedding.event_date).toLocaleDateString('en-US', {
              weekday: 'long', year: 'numeric',
              month: 'long', day: 'numeric'
            })}
          </p>
        )}
        {wedding?.venue_name && (
          <p className="text-gray-400 text-sm">📍 {wedding.venue_name}</p>
        )}
        <p className="text-sm text-gray-400 mt-2">
          {tables.length} tables · {totalGuests} guests
        </p>
      </div>

      {/* Tables Grid */}
      <div className="grid grid-cols-2 gap-6">
        {tables.map(table => {
          const count = getGuestCount(table)
          return (
            <div
              key={table.id}
              className="border border-gray-200 rounded-xl p-4"
            >
              <div className="flex items-center justify-between mb-3 pb-2 border-b border-gray-100">
                <h2 className="font-bold text-gray-800 text-lg">
                  {table.name}
                </h2>
                <span className="text-xs text-gray-400 font-medium">
                  {count} / {table.max_seats} seats
                </span>
              </div>
              <ol className="space-y-1.5">
                {table.seating_assignments.map((assignment, index) => (
                  <li
                    key={assignment.id}
                    className="flex items-center gap-2 text-sm"
                  >
                    <span className="text-gray-300 font-mono text-xs w-5">
                      {index + 1}.
                    </span>
                    <span className="text-gray-700">
                      {assignment.guests?.name}
                    </span>
                    {assignment.guests?.category === 'couple' && (
                      <span className="text-xs text-purple-400">(+1)</span>
                    )}
                  </li>
                ))}
                {table.seating_assignments.length === 0 && (
                  <li className="text-xs text-gray-300 italic">
                    No guests assigned
                  </li>
                )}
              </ol>
            </div>
          )
        })}
      </div>

      {/* Table Flash Cards */}
      <div className="mt-12 pt-8 border-t border-gray-200">
        <h2 className="text-xl font-bold text-gray-800 mb-6 text-center">
          Table Cards
        </h2>
        <div className="grid grid-cols-2 gap-4">
          {tables.map(table => (
            <div
              key={table.id}
              className="border-2 border-gray-800 rounded-xl p-5 text-center"
            >
              <p className="text-xs uppercase tracking-widest text-gray-400 mb-1">
                {wedding?.couple_names}
              </p>
              <h3 className="text-2xl font-bold text-gray-900 mb-3">
                {table.name}
              </h3>
              <div className="border-t border-gray-200 pt-3 text-left">
                {table.seating_assignments.map(a => (
                  <p key={a.id} className="text-sm text-gray-600 py-0.5">
                    {a.guests?.name}
                    {a.guests?.category === 'couple' && ' & partner'}
                  </p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-100 text-center">
        <p className="text-xs text-gray-300">
          Generated by WeddingInvite · {new Date().toLocaleDateString()}
        </p>
      </div>
    </div>
  )
}